# Test config file for robust Vaisala listener.

[common]

# debug_level can be ALL, INFO, WARNINGS, or ERRORS.
#  ALL prints debug messages, routine information, warnings and errors.
#  INFO prints routube information and higher.
#  WARNINGS prints only warnings and errors.
#  ERRORS prints only error messages.
debug_level = "ALL"

# Source is either "serial" or "network"
source = "network"

# Broadcast arriving data over network (for Vaisala monitor panel)?
# This cannot be used together with source = "network".
broadcast = true


[uploader]

# Settings for the InfluxDB database uploader.
host = "localhost"
port = 8086
database = "vaisalatest"
batch_size = 3
backup = true
backup_file = "backups.txt"


[broadcast]

# These settings are used if common.broadcast is set to true.
port = 42222
max_connections = 5


[listener.network]

# These settings are used when common.source is set to "network"
host = "localhost"
port = 42222
timeout = 10


[listener.serial]

# These settings are used when common.source is set to "serial".
device = "/dev/ttyUSB0"
timeout = 60


[parser.variables]

# These map variable names in the Vaisala broadcast to variables names
# in the InfluxDB database.
TAAVG1M = "temperature"
PR = "pressure"
WD = "wind_dir"
WS = "wind_speed"
SNOWDEPTH = "snow_depth"
# TODO: add the rest


[parser.tags]

# Any string variables defined here will be used as tags in the InfluxDB database.
station = "vaisala"
