# Test config file for robust Vaisala listener.

[common]

# debug_level can be ALL, INFO, WARNINGS, or ERRORS.
#  ALL prints debug messages, routine information, warnings and errors.
#  INFO prints routube information and higher.
#  WARNINGS prints only warnings and errors.
#  ERRORS prints only error messages.
debug_level = "ALL"


[uploader]

host = "localhost"
port = 8086
database = "vaisalatest"
batch_size = 3
backup = true
backup_file = "backups.txt"


[vaisala]

host = "localhost"
port = 42222
timeout = 10


[vaisala.variables]

TAAVG1M = "temperature"
PR = "pressure"
WD = "wind_dir"
WS = "wind_speed"
SNOWDEPTH = "snow_depth"
# TODO: add the rest


[vaisala.tags]

station = "vaisala"
