# Test config file for robust Vaisala listener.

[database]

host = "localhost"
port = 8086
database = "vaisalatest"
batch_size = 3
backup = true
backup_dir = "."

[vaisala]

host = "localhost"
port = 42222
timeout = 10

[variables]

TAAVG1M = "temperature"
PR = "pressure"
WD = "wind_dir"
WS = "wind_speed"
SNOWDEPTH = "snow_depth"
# TODO: add the rest

[variables.tags]

station = "vaisala"
