# Test config file for robust Vaisala listener.

[common]

# debug_level can be ALL, INFO, WARNINGS, or ERRORS.
#  ALL prints debug messages, routine information, warnings and errors.
#  INFO prints routube information and higher.
#  WARNINGS prints only warnings and errors.
#  ERRORS prints only error messages.

debug_level = "ALL"
source = "network"


# SETTINGS FOR THE UPLOADER

[uploader]

# Settings for the InfluxDB database uploader.
host = "localhost"
port = 8086
database = "testing"
batch_size = 10
backup = true
backup_file = "backups.txt"
user = ""
password = "PASSWORD HERE"



# SETTINGS FOR LOCAL TCP/IP SERVER

[broadcast]

active = true
port = 32222



# SETTINGS FOR THE LISTENER

[listener.network]

# These settings are used when common.source is set to "network"
host = "localhost"
port = 42222
timeout = 10


[listener.serial]

# These settings are used when common.source is set to "serial".
device = "/dev/ttyUSB0"
timeout = 60



# SETTINGS FOR THE PARSER

[parser]

include = ["PA", "WS", "WD", "TAAVG1M", "RHAVG1M", "DPAVG1M", "SRAVG1M", "SRRAVG1M", "PRFAVG1H", "SNOWDEPTH", "PR", "STATUS", "EXTDC"]
rename = false

[parser.variables]

# These map variable names in the Vaisala broadcast to variables names
# in the InfluxDB database.
TAAVG1M = "temperature"
PR = "pressure"
WD = "wind_dir"
WS = "wind_speed"
RHAVG1M = "rel_humidity"
DPAVG1M = "dew_point"
SNOWDEPTH = "snow_depth"
SRAVG1M = "solar_incident"
SRRAVG1M = "solar_reflected"
PRFAVG1H = "precipitation"
EXTDC = "supply_voltage"


[parser.tags]

# Any string variables defined here will be used as tags in the InfluxDB database.
station = "vaisala"
